sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: CONDA=true
    - os: linux
      python: '3.6'
      env: CONDA=true
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

script:
  - PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source travis_install_conda.sh numpy scipy numba;
  - conda config --add channels moble
  - conda config --set anaconda_upload yes
  - conda install -n root conda-build anaconda-client
  - conda build --token "$ANACONDA_TOKEN" conda

# This uses the ANACONDA_TOKEN environment variable.  To create a token optionally log in first:
#   > anaconda login
# Then, either check for a token you want to use with
#   > anaconda auth -l
# or just create a new one with
#   > anaconda auth -c -n SOME_TOKEN_NAME --max-age 307584000 --url https://anaconda.org/moble/${PACKAGE_NAME} --scopes "api:write api:read"
# Then go to the Travis-CI settings page for this package, and create the environment variable with that token.
# I stole these ideas from Yoav Ram <https://gist.github.com/yoavram/05a3c04ddcf317a517d5>


after_script:
  # if we do not unset this before we terminate the travis teardown will mark the entire job as failed
  - set +e

deploy:
  - provider: pypi
    user: moboyle79
    skip_upload_docs: true
    password:
      secure: D0OzSdZn5hWjXX5H41g4pnqme1TJaABKGmUpe14PGMaRf8DjisVMZStAsVVWfocxFqQX3gress+KKtxEvdySXxcfkXAp8VTBvZ+V/uzQQFSYmf5KFwTR/yywff7vdCO+eSHztIcdOhz8Uw2poL/f4/BmO9Y5OoHXJPTkvr6MbIk=
    on:
      distributions: sdist bdist_wheel
      repo: moble/spinsfast
      python: '3.6'
      condition: "${TRAVIS_OS_NAME:-linux} = 'linux'"
