package:
  name: spinsfast
  version: {{ environ.get('package_version', '104.1') }}

source:
  git_url: https://github.com/moble/spinsfast.git

build:
  detect_binary_files_with_prefix: true
  # script: python setup.py install

requirements:
  build:
    - python {{ python }}
    - numpy
    - fftw

  run:
    - python
    - numpy
    - fftw

about:
  home: 'http://astrophysics.physics.fsu.edu/~huffenbe/research/spinsfast/index.html'
  license: GPL
  summary: 'Fast and exact spin-s spherical-harmonic transforms'
