name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
      fail-fast: false
    if: >-
        !contains(github.event.head_commit.message, '[skip ci]')
        && !contains(github.event.head_commit.message, '[skip tests]')
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2

      - name: 'Build wheels'
        uses: pypa/cibuildwheel@v2.3.1

      - name: 'Upload wheels'
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl


  build_sdist:
    name: 'Build sdist'
    runs-on: ubuntu-latest
    if: >-
        !contains(github.event.head_commit.message, '[skip ci]')
        && !contains(github.event.head_commit.message, '[skip tests]')
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 'Make sdist'
        run: |
          python -m pip install oldest-supported-numpy
          python setup.py sdist

      - name: 'Upload sdist'
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz


  upload_pypi:
    name: 'Publish to PyPI'
    needs: [build_wheels, build_sdist]
    if: >-
        github.ref == 'refs/heads/main'
        && !contains(github.event.head_commit.message, '[no release]')
        && (success() || contains(github.event.head_commit.message, '[skip tests]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: 'Publish to PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
